" function {
    " Astyle {
        function! CodeFormat() abort
            if !executable('astyle')
                throw 'CodeFormat: astyle is not installed'
            endif
            let command = 'astyle --suffix=none'
            if &filetype ==# 'java' || &filetype ==# 'cpp'
                let command .= ' --style=java'
            endif
            let formatted = systemlist(command, join(getline(1, '$'), "\n") . (&endofline ? "\n" : ''))
            if v:shell_error || empty(formatted)
                throw 'CodeFormat: astyle failed; buffer and file were not changed'
            endif
            let view = winsaveview()
            call setline(1, formatted)
            if line('$') > len(formatted)
                call deletebufline('%', len(formatted) + 1, '$')
            endif
            call winrestview(view)
        endfunction
    " }
" }

" Environment {
    " Basics {
        set nocompatible        " 设置为vim模式
    " }
 " }

" General {
    syntax on                   " 语法高亮
    set background=dark         " 暗色主题
    filetype plugin on          " 开启文件类型插件
    "filetype plugin indent on   " 开启文件类型缩进插件
    set mouse=a                 " 鼠标可以自由定位
    "set mousehide              " 输入时隐藏光标
    scriptencoding utf-8        " vim Script的编码
    "set spell                  " 开启拼写检查
    set shortmess=atI           " 不显示捐赠信息

    " 编辑git commit message时，回到第一行（默认记录上次打开的位置）
    au FileType gitcommit au! BufEnter COMMIT_EDITMSG call setpos('.', [0, 1, 1, 0])

    if has('clipboard')
        if has('unnamedplus')   " 使用 + 剪贴板寄存器
            set clipboard=unnamed,unnamedplus
        else                    " 使用 * 剪贴板寄存器
            set clipboard=unnamed
        endif
    endif

    set autoread                " 文件变化时自动读入
    set confirm                 " 设置保存提示
    set noeb                    " 关闭提示声音
    set vb t_vb=                " 关置空错误铃声的终端代码
    au GuiEnter * set t_vb=     " 关闭GUI屏幕闪烁
    set magic                   " 正则不转义
    set nobackup                " 覆盖文件时不备份，这个备份文件会一直保存
    set nowritebackup           " 覆盖文件时不备份，这个备份文件会在覆盖写入成功后删除
    set noswapfile              " 没有swap文件
    set autochdir               " 自动切换当前目录为当前文件所在的目录
" }

" Vim UI
    set guifont=Monospace\ 10
    set guioptions-=T           " 隐藏工具栏
    set guioptions-=m           " 隐藏菜单栏
    set showmode                " 左下角显示当前的wim模式
    set cursorline              " 高亮当前行
    "set cursorcolumn            " 高亮当前列

    if has('cmdline_info')
        set ruler               " 显示光标所在的行和列，以逗号分割
        set rulerformat=%30(%=\:b%n%y%m%r%w\ %l,%c%V\ %P%)      " 设置标尺显示的格式
        set showcmd             " 状态栏显示当前正在输入的命令
    endif

    if has('statusline')
        set laststatus=2        " 总是显示状态栏
    endif

    set backspace=indent,eol,start  " 退格键可删除缩进，上一行结束和插入符前面的文字
    set number                      " 显示行号
    set showmatch                   " 插入括号时，短暂地跳转到匹配的对应括号
    set incsearch                   " 搜索过程中显示搜索结果
    set hlsearch                    " 搜索时高亮显示搜索到的文本
    set winminheight=0              " 窗口最小高度可为0行
    set ignorecase                  " 忽略大小写
    set smartcase                   " 在有一个或多个大写字母时保持大小写敏感
    set wildmenu                    " 补全时弹出菜单而不是直接补全
    set wildmode=list:longest,full  " Tab自动补全时的顺序
    "set whichwrap=b,s,h,l,<,>,[,]  " 允许跨行移动光标
    set list                        " 高亮显示特殊字符
    set listchars=tab:›\ ,trail:•,extends:#,nbsp:.      " 高亮显示哪些特殊字符
    set cmdheight=2                 " Command-line 高度
    if (empty($TMUX))
        if (has("termguicolors"))
            set termguicolors
        endif
    endif
" }

" Formatting {
    set nowrap                      " 不自动换行
    "set smartindent                 " 开启新行时使用智能自动缩进，会被cindent覆盖
    "set autoindent                  " 开启新行时复制当前行的缩进
    set shiftwidth=4                " 设置Shift+<<和Shift+>>缩进时的宽度
    set expandtab                   " 用空格表示tab
    set smarttab                    " 插入行首tab时其宽度参考shiftwidth的值
    set tabstop=4                   " 一个tab代表4个空格
    set softtabstop=4               " 退格键可以一次性删掉4个空格（代表一个tab）
    set nojoinspaces                " 用J命令合并两行时会用一个空格来分隔，如果去掉no则是两个空格
    set splitright                  " 用vsplit新建窗口时，新的窗口出现在右边
    set splitbelow                  " 用split新建窗口时，新的窗口出现在下边
    set encoding=utf-8              " 字符编码
    set ffs=unix,dos,mac            " 文件格式，决定行尾字符
    autocmd FileType haskell,puppet,ruby,yml setlocal expandtab shiftwidth=2 softtabstop=2
" }

" Plugins {
    " Plugin packages are pinned and supplied by Home Manager/Nix.
    " Tagbar {
        let g:tagbar_width=45
        let g:tagbar_autofocus=1
        "autocmd vimenter * Tagbar
        nmap <F6> :TagbarToggle<cr>
    " }

    " the NERD Tree {
        "autocmd vimenter * NERDTree    " 自动打开文件列表
        let NERDTreeWinPos="left"
        nmap <F7> :NERDTreeToggle<CR>
    " }

    " vim-airline {
        set t_Co=255
        let g:airline#extensions#tabline#enabled = 1
        let g:airline#extensions#tabline#buffer_nr_show = 1
        let g:airline#extensions#tabline#formatter = 'unique_tail'
    " }

    " indentLine {
        let g:indentLine_char = '┆'
        map <F8> :IndentLinesToggle<CR>
        let g:indentLine_concealcursor=""
    " }

    " syntastic {
        set statusline+=%#warningmsg#
        set statusline+=%{SyntasticStatuslineFlag()}
        set statusline+=%*
        let g:syntastic_always_populate_loc_list = 1
        "let g:syntastic_auto_loc_list = 1
        let g:syntastic_check_on_open = 1
        let g:syntastic_check_on_wq = 0
    " }

    " DoxygenToolkit.vim {
        let g:DoxygenToolkit_authorName="hsingyun"
        let g:DoxygenToolkit_licenseTag="Apache Licence 2.0"
    " }

    " vim-json {
        let g:vim_json_syntax_conceal = 0
    " }

    " neocomplete.vim {
        if has("lua")
            let g:neocomplete#enable_at_startup = 1
        endif
    " }

    " neoformat {
        "map <C-S-F> ::Neoformat<CR>       "映射代码格式化函数到shift+f快捷键
    " }

    " ctrlsf {
        nnoremap <C-f> :CtrlSF<Space>
        let g:ctrlsf_default_view_mode = 'compact'
    " }

    " 默认编辑窗口 {
        wincmd w
        autocmd VimEnter * wincmd w
    " }
" }

" keyMaps {
    nmap <C-X> :bwipe<CR>       " Ctrl+X 表示清除缓存区
    noremap <C-A> gggH<C-O>G
    inoremap <C-A> <C-O>gg<C-O>gH<C-O>G
    cnoremap <C-A> <C-C>gggH<C-O>G
    onoremap <C-A> <C-C>gggH<C-O>G
    snoremap <C-A> <C-C>gggH<C-O>G
    vnoremap <BS> d
    vnoremap <C-X> "+x
    vnoremap <C-C> "+y
    map <C-V> "+gP
    cmap <C-V> <C-R>+
    nnoremap <F2> :bp<CR>
    nnoremap <F3> :bn<CR>
" }
